Repository MarquezProject/marquez, pull requests merged in 2018-09, with the labels that each got.

#65 Add support for job_run and job_run_state creation workflows
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/api/CreateJobRunRequest.java
  src/main/java/marquez/api/CreateJobRunResponse.java
  src/main/java/marquez/api/GetJobRunResponse.java
  src/main/java/marquez/api/Job.java
  src/main/java/marquez/api/JobRun.java
  src/main/java/marquez/api/JobRunState.java
  src/main/java/marquez/api/UpdateJobRunRequest.java
  src/main/java/marquez/api/UpdateJobRunResponse.java
  src/main/java/marquez/db/dao/JobDAO.java
  src/main/java/marquez/db/dao/JobRow.java
  src/main/java/marquez/db/dao/JobRunDAO.java
  src/main/java/marquez/db/dao/JobRunRow.java
  src/main/java/marquez/db/dao/JobRunStateDAO.java
  src/main/java/marquez/db/dao/JobRunStateRow.java
  src/main/java/marquez/resources/BaseResource.java
  src/main/java/marquez/resources/JobRunResource.java
  src/main/resources/db/migration/V3__add_job_run_definitions.sql
  src/main/resources/db/migration/V4__adjust_job_run_definitions.sql
  src/test/java/marquez/MarquezAppIntegrationTest.java
  src/test/java/marquez/TestJobSerialization.java
  src/test/java/marquez/api/DatasetSerializationTest.java
  src/test/java/marquez/api/JobRunBaseTest.java
  src/test/java/marquez/api/JobRunDaoTest.java
  src/test/java/marquez/api/JobRunIntegrationTest.java
  src/test/java/marquez/api/JobRunStateTest.java
  src/test/java/marquez/api/JobRunStateTransitionTest.java
  src/test/java/marquez/api/JobRunTest.java
  src/test/java/marquez/api/JobTest.java
Labels: ready

#64 create Job Run Definition endpoint
  .vscode/last.sql
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/api/Job.java
  src/main/java/marquez/api/JobRunDefinition.java
  src/main/java/marquez/api/JobVersion.java
  src/main/java/marquez/api/entities/CreateJobRunDefinitionRequest.java
  src/main/java/marquez/api/entities/CreateJobRunDefinitionResponse.java
  src/main/java/marquez/api/entities/ErrorResponse.java
  src/main/java/marquez/api/entities/GetJobRunDefinitionResponse.java
  src/main/java/marquez/db/dao/JobDAO.java
  src/main/java/marquez/db/dao/JobRow.java
  src/main/java/marquez/db/dao/JobRunDefinitionDAO.java
  src/main/java/marquez/db/dao/JobRunDefinitionRow.java
  src/main/java/marquez/db/dao/JobVersionDAO.java
  src/main/java/marquez/db/dao/JobVersionRow.java
  src/main/java/marquez/resources/BaseResource.java
  src/main/java/marquez/resources/JobRunDefinitionResource.java
  src/main/resources/db/migration/V3__add_job_run_definitions.sql
  src/test/java/marquez/MarquezAppIntegrationTest.java
  src/test/java/marquez/api/JobRunBaseTest.java
  src/test/java/marquez/api/JobVersionTest.java
  src/test/java/marquez/db/dao/JobRunDefinitionDAOTest.java
  src/test/java/marquez/resources/JobRunDefinitionResourceTest.java
Labels: in progress

#79 [MARQUEZ-76]: Add explicit collections types to avoid compiler warnings
  src/main/java/marquez/api/JobRunState.java
Labels: ready

#78 Replace h2 with embedded postgres for testing
  build.gradle
  src/main/resources/db/migration/V4__adjust_job_run_definitions.sql
  src/test/java/marquez/MarquezAppIntegrationTest.java
  src/test/java/marquez/api/JobRunBaseTest.java
  src/test/java/marquez/api/JobRunDaoTest.java
  src/test/java/marquez/api/JobRunIntegrationTest.java
  src/test/java/marquez/db/dao/TestOwnerDAO.java
  src/test/java/marquez/db/dao/fixtures/ConfigExportingPreparedDbRule.java
  src/test/java/marquez/db/dao/fixtures/DAOSetup.java
  src/test/resources/config.h2.test.yml
Labels: ready

#82 Add support to enable variable substitution with environment variables
  src/main/java/marquez/MarquezApp.java
Labels: enhancement, ready
