Repository MarquezProject/marquez, pull requests merged in 2018-08, with the labels that each got.

#14 Add job resource
  scripts/run.sh
  src/main/java/marquez/MarquezApplication.java
  src/main/java/marquez/MarquezConfiguration.java
  src/main/java/marquez/api/Job.java
  src/main/java/marquez/api/Ownership.java
  src/main/java/marquez/db/dao/JobDAO.java
  src/main/java/marquez/db/dao/JobRow.java
  src/main/java/marquez/db/dao/OwnerDAO.java
  src/main/java/marquez/db/dao/OwnershipDAO.java
  src/main/java/marquez/resources/BaseResource.java
  src/main/java/marquez/resources/JobResource.java
  src/main/java/marquez/resources/OwnerResource.java
  src/main/resources/db/migration/V1__create_tables.sql
  src/test/java/marquez/TestJobSerialization.java
  src/test/java/marquez/resources/JobResourceTest.java
Labels: in progress

#38 Readd checkstyle
  build.gradle
  checkstyle.xml
Labels: ready

#27 implement get, delete for owner and improve tests
  src/main/java/marquez/db/dao/OwnerDAO.java
  src/main/java/marquez/db/dao/OwnerRow.java
  src/main/java/marquez/resources/OwnerResource.java
  src/main/resources/db/migration/V2__add_owner_deletedat.sql
  src/test/java/marquez/api/TestOwner.java
  src/test/java/marquez/db/dao/TestOwnerDAO.java
Labels: ready

#43 Bump jdbi3 dep to 3.4.0
  build.gradle
Labels: ready

#41 Add snyk vulnerabilities badge
  README.md
Labels: ready

#42 Add db migration on app startup
  build.gradle
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/MarquezConfig.java
  src/main/resources/db/migration/V1__initial_schema.sql.sql
  src/test/java/marquez/MarquezAppIntegrationTest.java
  src/test/java/marquez/db/dao/fixtures/DAOSetup.java
  src/test/resources/config.test.yml
Labels: cleanup

#52 Remove run.sh
  scripts/run.sh
Labels: cleanup, ready
