Repository MarquezProject/marquez, pull requests merged in 2018-11, with the labels that each got.

#129 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: review

#133 Adding docker compose
  docker-compose.yml
  docker/create_database.sh
Labels: review

#135 Update docker compose
  config.example.yml
  docker-compose.yml
  docker/create_database.sh
  docker/entrypoint.sh
  docker/initdb.sh
  docker/wait-for-it.sh
Labels: review

#134 Add mailing list to README.md
  CONTRIBUTING.md
  README.md
Labels: review

#137 Add @marquez-user and @marquez-dev mailing lists
  README.md
Labels: review

#126 banner to indicate when endpoints have loaded
  src/main/resources/banner.txt
Labels: review

#139 Add link to website [skip ci]
  README.md
Labels: review

#141 Update marquez description [skip ci]
  README.md
Labels: review

#143 Minor update to config section [skip ci]
  README.md
Labels: review

#144 Add how to contribute section in CONTRIBUTING.md [skip ci]
  CONTRIBUTING.md
Labels: review

#145 Fix data serialization test
  src/test/java/marquez/api/DatasetSerializationTest.java
Labels: ready, review

#132 First pass at error handling code
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/api/CreateNamespaceRequest.java
  src/main/java/marquez/api/CreateNamespaceResponse.java
  src/main/java/marquez/api/GetNamespaceResponse.java
  src/main/java/marquez/api/ListNamespacesResponse.java
  src/main/java/marquez/api/Namespace.java
  src/main/java/marquez/api/validation/.keep
  src/main/java/marquez/core/exceptions/.keep
  src/main/java/marquez/core/exceptions/ResourceException.java
  src/main/java/marquez/core/exceptions/UnexpectedException.java
  src/main/java/marquez/core/mappers/CoreNamespaceToApiNamespaceMapper.java
  src/main/java/marquez/core/mappers/GetNamespaceResponseMapper.java
  src/main/java/marquez/core/mappers/ResourceExceptionMapper.java
  src/main/java/marquez/core/models/Namespace.java
  src/main/java/marquez/core/services/NamespaceService.java
  src/main/java/marquez/resources/NamespaceResource.java
  src/main/resources/db/migration/V5__schema_updates_for_0-1-0.sql
  src/test/java/marquez/NamespaceBaseTest.java
  src/test/java/marquez/api/DatasetSerializationTest.java
  src/test/java/marquez/api/NamespaceIntegrationTest.java
  src/test/java/marquez/api/NamespaceTest.java
  src/test/java/marquez/resources/NamespaceResourceTest.java
Labels: review

#104 Add openapi.yml [skip ci]
  docs/openapi.yml
Labels: in progress

#153 Bump mockito-core to 2.23.4
  build.gradle
Labels: review

#151 Bump jdbi3 to 3.5.1
  build.gradle
Labels: review

#150 Define plugin with single quotes
  build.gradle
Labels: review

#152 Bump postgresql to 42.2.5
  build.gradle
Labels: review

#148 Fix logger for MarquezApp class
  src/main/java/marquez/MarquezApp.java
Labels: review

#161 Bump gradle to 4.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: review

#162 Bump spotless plugin to 3.16.0
  build.gradle
Labels: review

#147 Update job output req body in openapi spec [skip ci]
  docs/.keep
  docs/openapi.yml
Labels: review

#164 Bump shadow plugin to 4.0.3
  build.gradle
Labels: review

#155 Add optional method to mapper
  src/main/java/marquez/api/ListNamespacesResponse.java
  src/main/java/marquez/core/mappers/CoreNamespaceToApiNamespaceMapper.java
  src/main/java/marquez/core/mappers/GetNamespaceResponseMapper.java
  src/main/java/marquez/core/mappers/Mapper.java
  src/main/java/marquez/resources/NamespaceResource.java
  src/test/java/marquez/core/mappers/MapperTest.java
  src/test/java/marquez/resources/NamespaceResourceTest.java
Labels: enhancement, review

#167 Use wait-for-db.sh instead of wait-for-it.sh
  Dockerfile
  docker-compose.yml
  docker/build-and-push.sh
  docker/common.sh
  docker/entrypoint.sh
  docker/init-marquezdb.sh
  docker/login.sh
  docker/wait-for-db.sh
  docker/wait-for-it.sh
Labels: review

#168 Update init-marquezdb.sh usage
  docker/init-marquezdb.sh
Labels: review

#169 Rename init-marquezdb.sh to init-db.sh
  docker-compose.yml
  docker/init-db.sh
Labels: review

#171 Copy example config on docker-compose up [skip ci]
  docker-compose.yml
Labels: review

#174 Add extra space for readability in common.sh
  docker/common.sh
Labels: review
