Repository MarquezProject/marquez, pull requests merged in 2018-12, with the labels that each got.

#173 Move mapper to marquez.common pkg
  src/main/java/marquez/common/Mapper.java
  src/test/java/marquez/common/MapperTest.java
Labels: cleanup, enhancement, review

#175 update runArgs to be string
  docs/openapi.yml
Labels: review

#149 Add empty dirs for new app structure
  src/main/java/marquez/api/exceptions/.keep
  src/main/java/marquez/api/health/.keep
  src/main/java/marquez/api/mappers/.keep
  src/main/java/marquez/api/models/.keep
  src/main/java/marquez/api/resources/.keep
  src/main/java/marquez/api/validators/.keep
  src/main/java/marquez/common/.keep
  src/main/java/marquez/db/.keep
  src/main/java/marquez/db/models/.keep
  src/main/java/marquez/health/.keep
  src/main/java/marquez/service/exceptions/.keep
  src/main/java/marquez/service/mappers/.keep
  src/main/java/marquez/service/models/.keep
Labels: enhancement, review

#192 Implement namespace service
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/api/ListNamespacesResponse.java
  src/main/java/marquez/core/mappers/NamespaceApiMapper.java
  src/main/java/marquez/core/services/NamespaceService.java
  src/main/java/marquez/dao/NamespaceDAO.java
  src/main/java/marquez/dao/NamespaceRow.java
  src/main/java/marquez/resources/NamespaceResource.java
  src/test/java/marquez/api/NamespaceIntegrationTest.java
  src/test/java/marquez/core/models/Generator.java
  src/test/java/marquez/core/services/NamespaceServiceTest.java
  src/test/java/marquez/dao/NamespaceDAOTest.java
  src/test/java/marquez/resources/NamespaceResourceTest.java
Labels: review

#187 Added resource-layer changes
  .editorconfig
  .gitignore
  build.gradle
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/api/CreateJobRequest.java
  src/main/java/marquez/api/CreateJobRunRequest.java
  src/main/java/marquez/api/CreateJobRunResponse.java
  src/main/java/marquez/api/CreateNamespaceRequest.java
  src/main/java/marquez/api/CreateNamespaceResponse.java
  src/main/java/marquez/api/ErrorResponse.java
  src/main/java/marquez/api/GetJobRunResponse.java
  src/main/java/marquez/api/Job.java
  src/main/java/marquez/api/JobRun.java
  src/main/java/marquez/api/JobRunState.java
  src/main/java/marquez/api/ListJobsResponse.java
  src/main/java/marquez/api/ListNamespacesResponse.java
  src/main/java/marquez/api/Namespace.java
  src/main/java/marquez/api/Ownership.java
  src/main/java/marquez/api/UpdateJobRunRequest.java
  src/main/java/marquez/api/UpdateJobRunResponse.java
  src/main/java/marquez/core/mappers/ApiJobToCoreJobMapper.java
  src/main/java/marquez/core/mappers/CoreJobRunToApiJobRunMapper.java
  src/main/java/marquez/core/mappers/CoreJobToApiJobMapper.java
  src/main/java/marquez/core/mappers/CoreNamespaceToApiNamespaceMapper.java
  src/main/java/marquez/core/mappers/NamespaceApiMapper.java
  src/main/java/marquez/core/models/Job.java
  src/main/java/marquez/dao/DatasetDAO.java
  src/main/java/marquez/dao/JobDAO.java
  src/main/java/marquez/dao/JobRunStateDAO.java
  src/main/java/marquez/dao/JobRunStateRow.java
  src/main/java/marquez/dao/OwnershipDAO.java
  src/main/java/marquez/dao/deprecated/DatasetDAO.java
  src/main/java/marquez/dao/deprecated/DbDAO.java
  src/main/java/marquez/dao/deprecated/JobDAO.java
  src/main/java/marquez/dao/deprecated/JobRow.java
  src/main/java/marquez/dao/deprecated/JobRunDAO.java
  src/main/java/marquez/dao/deprecated/JobRunRow.java
  src/main/java/marquez/dao/deprecated/JobRunStateDAO.java
  src/main/java/marquez/dao/deprecated/JobRunStateRow.java
  src/main/java/marquez/dao/deprecated/OwnershipDAO.java
  src/main/java/marquez/resources/DatasetResource.java
  src/main/java/marquez/resources/JobResource.java
  src/main/java/marquez/resources/JobRunResource.java
  src/main/java/marquez/resources/NamespaceResource.java
  src/test/java/marquez/MarquezAppIntegrationTest.java
  src/test/java/marquez/api/DatasetSerializationTest.java
  src/test/java/marquez/api/JobIntegrationTest.java
  src/test/java/marquez/api/JobResourceTest.java
  src/test/java/marquez/api/JobRunBaseTest.java
  src/test/java/marquez/api/JobRunDaoTest.java
  src/test/java/marquez/api/JobRunIntegrationTest.java
  src/test/java/marquez/api/JobRunStateTest.java
  src/test/java/marquez/api/JobRunStateTransitionTest.java
  src/test/java/marquez/api/JobRunTest.java
  src/test/java/marquez/api/JobTest.java
  src/test/java/marquez/api/NamespaceIntegrationTest.java
  src/test/java/marquez/dao/JobRunDaoTest.java
  src/test/java/marquez/dao/deprecated/JobDAOTest.java
  src/test/java/marquez/resources/JobResourceTest.java
  src/test/java/marquez/resources/NamespaceResourceTest.java
Labels: in progress

#205 Redefine unique jobs idx
  src/main/resources/db/migration/V8__update_run_args.sql
  src/test/java/marquez/dao/JobDAOTest.java
Labels: review

#228 Update CONTRIBUTING.md [skip ci]
  CONTRIBUTING.md
  README.md
Labels: review

#222 List env vars in configuration section [skip ci]
  README.md
Labels: review
