Repository MarquezProject/marquez, pull requests merged in 2019-03, with the labels that each got.

#357 Add gitter badge [ci skip]
  README.md
Labels: review

#370 Add @NoArgsConstructor to exceptions
  src/main/java/marquez/MarquezException.java
  src/main/java/marquez/service/exceptions/MarquezServiceException.java
Labels: cleanup

#382 Update annotations in API models
  src/main/java/marquez/api/mappers/NamespaceApiMapper.java
  src/main/java/marquez/api/models/JobRequest.java
  src/main/java/marquez/api/models/JobRunRequest.java
  src/main/java/marquez/api/models/NamespaceRequest.java
  src/main/java/marquez/api/resources/JobResource.java
Labels: api, cleanup

#371 Add class MarquezServiceExceptionMapper
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/api/exceptions/.keep
  src/main/java/marquez/api/exceptions/MarquezServiceExceptionMapper.java
  src/main/java/marquez/api/exceptions/ResourceException.java
  src/main/java/marquez/api/models/ErrorResponse.java
  src/main/java/marquez/api/resources/JobResource.java
  src/main/java/marquez/api/resources/NamespaceResource.java
  src/test/java/marquez/api/JobResourceTest.java
  src/test/java/marquez/api/resources/NamespaceResourceTest.java
Labels: api, cleanup, review

#400 Use default compose network
  docker-compose.yml
Labels: cleanup, review

#397 [Datasource Service - Part 4]: Adjust datasource create response code
  src/main/java/marquez/api/resources/DatasourceResource.java
  src/test/java/marquez/api/resources/DatasourceResourceTest.java
  src/test/java/marquez/db/DatasourceDaoTest.java
Labels: review

#387 [Datasource Service - Part 2]: Add get endpoint for datasources
  src/main/java/marquez/api/exceptions/DatasourceUrnNotFoundException.java
  src/main/java/marquez/api/mappers/DatasourceResponseMapper.java
  src/main/java/marquez/api/models/DatasourceResponse.java
  src/main/java/marquez/api/resources/DatasourceResource.java
  src/main/java/marquez/common/models/ConnectionUrl.java
  src/main/java/marquez/common/models/DatasourceType.java
  src/main/java/marquez/common/models/DatasourceUrn.java
  src/main/java/marquez/common/models/Urn.java
  src/main/java/marquez/db/DatasetDao.java
  src/main/java/marquez/db/DatasourceDao.java
  src/main/java/marquez/db/mappers/DatasourceRowMapper.java
  src/main/java/marquez/db/models/DatasourceRow.java
  src/main/java/marquez/service/DatasourceService.java
  src/main/java/marquez/service/mappers/DatasourceMapper.java
  src/main/java/marquez/service/mappers/DatasourceRowMapper.java
  src/main/java/marquez/service/models/Datasource.java
  src/main/resources/db/migration/V10__fix_datasources.sql
  src/test/java/marquez/api/resources/DatasourceResourceTest.java
  src/test/java/marquez/common/models/ConnectionUrlTest.java
  src/test/java/marquez/common/models/DatasourceTypeTest.java
  src/test/java/marquez/common/models/DatasourceUrnTest.java
  src/test/java/marquez/common/models/UrnTest.java
  src/test/java/marquez/db/DatasetDaoTest.java
  src/test/java/marquez/db/DatasourceDaoTest.java
  src/test/java/marquez/db/mappers/DatasourceRowMapperTest.java
  src/test/java/marquez/db/models/DatasourceRowTest.java
  src/test/java/marquez/service/DatasourceServiceTest.java
  src/test/java/marquez/service/mappers/DatasourceMapperTest.java
  src/test/java/marquez/service/mappers/DatasourceRowMapperTest.java
  src/test/java/marquez/service/models/Generator.java
Labels: in progress

#398 Cleanup class DatasourceUrn and DatasetUrn
  src/main/java/marquez/common/models/DatasetUrn.java
  src/main/java/marquez/common/models/DatasourceName.java
  src/main/java/marquez/common/models/DatasourceType.java
  src/main/java/marquez/common/models/DatasourceUrn.java
  src/main/java/marquez/common/models/Urn.java
  src/main/java/marquez/common/models/UrnPattern.java
  src/test/java/marquez/common/models/DatasetUrnTest.java
  src/test/java/marquez/common/models/DatasourceNameTest.java
  src/test/java/marquez/common/models/DatasourceUrnTest.java
  src/test/java/marquez/common/models/UrnPatternTest.java
  src/test/java/marquez/common/models/UrnTest.java
Labels: cleanup, common, enhancement, review

#406 Add compiler arg flag -parameters to compileTestJava
  build.gradle
Labels: review

#411 Bump mockito-core to 2.25.1
  build.gradle
Labels: review

#410 Bump lombok to 1.18.6
  build.gradle
Labels: review

#409 Bump spotless plugin to 3.20.0
  build.gradle
Labels: review

#415 Update NamespaceService and NamespaceDao interface
  src/main/java/marquez/api/resources/DatasetResource.java
  src/main/java/marquez/api/resources/JobResource.java
  src/main/java/marquez/api/resources/NamespaceResource.java
  src/main/java/marquez/db/NamespaceDao.java
  src/main/java/marquez/service/NamespaceService.java
  src/test/java/marquez/api/JobResourceTest.java
  src/test/java/marquez/api/resources/DatasetResourceTest.java
  src/test/java/marquez/api/resources/NamespaceResourceTest.java
  src/test/java/marquez/db/NamespaceDaoTest.java
  src/test/java/marquez/service/NamespaceServiceTest.java
Labels: cleanup, enhancement, review

#416 Move tests to correct pkg
  src/test/java/marquez/api/JobRunResponseTest.java
  src/test/java/marquez/api/JobTest.java
  src/test/java/marquez/api/resources/JobIntegrationTest.java
  src/test/java/marquez/api/resources/JobResourceTest.java
  src/test/java/marquez/api/resources/JobRunBaseTest.java
  src/test/java/marquez/api/resources/NamespaceIntegrationTest.java
  src/test/java/marquez/db/JobRunDaoTest.java
  src/test/java/marquez/service/models/NamespaceTest.java
Labels: cleanup, review

#414 Fix exception annotations
  src/main/java/marquez/MarquezException.java
  src/main/java/marquez/api/exceptions/DatasourceUrnNotFoundException.java
  src/main/java/marquez/api/exceptions/MarquezServiceExceptionMapper.java
  src/main/java/marquez/service/exceptions/MarquezServiceException.java
Labels: cleanup, review

#417 Default Description.NO_VALUE to null
  src/main/java/marquez/api/models/DatasetVersionRequest.java
  src/main/java/marquez/api/models/DbTableVersionRequest.java
  src/main/java/marquez/common/models/Description.java
  src/main/java/marquez/service/mappers/DatasetRowMapper.java
  src/main/resources/db/migration/V11__remove_not_null_description_column_contraint.sql
  src/test/java/marquez/api/mappers/DatasetResponseMapperTest.java
  src/test/java/marquez/common/models/DescriptionTest.java
Labels: cleanup, common, review

#431 Add db column helper methods
  src/main/java/marquez/db/Columns.java
  src/main/java/marquez/db/mappers/DatasetRowMapper.java
  src/main/java/marquez/db/mappers/JobRowMapper.java
  src/main/java/marquez/db/mappers/JobVersionRowMapper.java
  src/test/java/marquez/db/ColumnsTest.java
Labels: enhancement
