Repository MarquezProject/marquez, pull requests merged in 2019-02, with the labels that each got.

#272 Bump spotless 3.17.0
  build.gradle
Labels: review

#271 Add preconditions
  src/main/java/marquez/common/Preconditions.java
  src/test/java/marquez/common/PreconditionsTest.java
Labels: enhancement

#270 Remove core pkg
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/api/exceptions/ResourceException.java
  src/main/java/marquez/api/exceptions/ResourceExceptionMapper.java
  src/main/java/marquez/api/mappers/ApiJobToCoreJobMapper.java
  src/main/java/marquez/api/mappers/CoreJobRunToApiJobRunResponseMapper.java
  src/main/java/marquez/api/mappers/CoreJobToApiJobMapper.java
  src/main/java/marquez/api/mappers/CoreNamespaceToApiNamespaceMapper.java
  src/main/java/marquez/api/mappers/Mapper.java
  src/main/java/marquez/api/mappers/NamespaceApiMapper.java
  src/main/java/marquez/api/mappers/NamespaceResponseMapper.java
  src/main/java/marquez/api/resources/DatasetResource.java
  src/main/java/marquez/api/resources/JobResource.java
  src/main/java/marquez/api/resources/NamespaceResource.java
  src/main/java/marquez/core/exceptions/.keep
  src/main/java/marquez/core/models/.keep
  src/main/java/marquez/db/JobDao.java
  src/main/java/marquez/db/JobRunArgsDao.java
  src/main/java/marquez/db/JobRunDao.java
  src/main/java/marquez/db/JobRunStateDao.java
  src/main/java/marquez/db/JobVersionDao.java
  src/main/java/marquez/db/NamespaceDao.java
  src/main/java/marquez/db/mappers/JobRowMapper.java
  src/main/java/marquez/db/mappers/JobRunArgsRowMapper.java
  src/main/java/marquez/db/mappers/JobRunRowMapper.java
  src/main/java/marquez/db/mappers/JobRunStateRowMapper.java
  src/main/java/marquez/db/mappers/JobVersionRowMapper.java
  src/main/java/marquez/db/mappers/NamespaceRowMapper.java
  src/main/java/marquez/service/DatasetService.java
  src/main/java/marquez/service/JobService.java
  src/main/java/marquez/service/NamespaceService.java
  src/main/java/marquez/service/exceptions/NamespaceException.java
  src/main/java/marquez/service/exceptions/UnexpectedException.java
  src/main/java/marquez/service/models/Job.java
  src/main/java/marquez/service/models/JobRun.java
  src/main/java/marquez/service/models/JobRunState.java
  src/main/java/marquez/service/models/JobVersion.java
  src/main/java/marquez/service/models/Namespace.java
  src/main/java/marquez/service/models/RunArgs.java
  src/test/java/marquez/api/JobIntegrationTest.java
  src/test/java/marquez/api/JobResourceTest.java
  src/test/java/marquez/api/JobRunResponseTest.java
  src/test/java/marquez/api/NamespaceTest.java
  src/test/java/marquez/api/mappers/NamespaceResponseMapperTest.java
  src/test/java/marquez/api/resources/DatasetResourceTest.java
  src/test/java/marquez/api/resources/NamespaceBaseTest.java
  src/test/java/marquez/api/resources/NamespaceResourceTest.java
  src/test/java/marquez/db/JobDaoTest.java
  src/test/java/marquez/db/JobRunArgsDaoTest.java
  src/test/java/marquez/db/JobRunDaoTest.java
  src/test/java/marquez/db/JobVersionDaoTest.java
  src/test/java/marquez/db/NamespaceDaoTest.java
  src/test/java/marquez/service/JobServiceIntegrationTest.java
  src/test/java/marquez/service/JobServiceTest.java
  src/test/java/marquez/service/NamespaceServiceTest.java
  src/test/java/marquez/service/models/Generator.java
Labels: cleanup, review

#287 Remove common.sh
  Dockerfile
  docker/build-and-push.sh
  docker/common.sh
  docker/wait-for-db.sh
Labels: cleanup, review

#310 Fix CI release job
  .circleci/config.yml
Labels: review

#266 fix dataset list error
  src/main/java/marquez/api/resources/DatasetResource.java
  src/main/java/marquez/db/DataSourceDao.java
  src/main/java/marquez/db/DatasetDao.java
  src/main/java/marquez/db/DbTableInfoDao.java
  src/main/java/marquez/db/DbTableVersionDao.java
  src/main/java/marquez/db/mappers/DataSourceRowMapper.java
  src/main/java/marquez/db/mappers/DatasetRowMapper.java
  src/main/java/marquez/db/models/DataSourceRow.java
  src/main/java/marquez/db/models/DatasetRow.java
  src/main/java/marquez/db/models/DbTableInfoRow.java
  src/main/java/marquez/db/models/DbTableVersionRow.java
  src/main/java/marquez/service/mappers/DataSourceRowMapper.java
  src/main/resources/db/migration/V9__fix_datasources.sql
  src/test/java/marquez/db/DatasetDaoTest.java
  src/test/java/marquez/service/mappers/DataSourceRowMapperTest.java
  src/test/java/marquez/service/models/Generator.java
Labels: in progress

#323 Update data source row mapper test
  src/test/java/marquez/service/mappers/DataSourceRowMapperTest.java
Labels: review

#333 Add column constants
  src/main/java/marquez/db/Columns.java
  src/main/java/marquez/db/mappers/DataSourceRowMapper.java
  src/main/java/marquez/db/mappers/DatasetRowMapper.java
  src/main/java/marquez/db/mappers/DbTableInfoRowMapper.java
  src/main/java/marquez/db/mappers/DbTableVersionRowMapper.java
  src/main/java/marquez/db/mappers/JobRowMapper.java
  src/main/java/marquez/db/mappers/JobRunArgsRowMapper.java
  src/main/java/marquez/db/mappers/JobRunRowMapper.java
  src/main/java/marquez/db/mappers/JobRunStateRowMapper.java
  src/main/java/marquez/db/mappers/JobVersionRowMapper.java
  src/main/java/marquez/db/mappers/NamespaceRowMapper.java
  src/test/java/marquez/db/ColumnsTest.java
  src/test/java/marquez/db/mappers/DataSourceRowMapperTest.java
Labels: cleanup, review

#324 Update data source row class
  src/main/java/marquez/db/models/DataSourceRow.java
  src/test/java/marquez/db/mappers/DataSourceRowMapperTest.java
  src/test/java/marquez/db/models/DataSourceRowTest.java
Labels: db, review

#340 Add MarquezServiceException
  src/main/java/marquez/MarquezException.java
  src/main/java/marquez/api/resources/DatasetResource.java
  src/main/java/marquez/api/resources/JobResource.java
  src/main/java/marquez/api/resources/NamespaceResource.java
  src/main/java/marquez/service/DatasetService.java
  src/main/java/marquez/service/JobService.java
  src/main/java/marquez/service/NamespaceService.java
  src/main/java/marquez/service/exceptions/.keep
  src/main/java/marquez/service/exceptions/MarquezServiceException.java
  src/test/java/marquez/api/JobIntegrationTest.java
  src/test/java/marquez/api/JobResourceTest.java
  src/test/java/marquez/api/resources/DatasetResourceTest.java
  src/test/java/marquez/api/resources/NamespaceResourceTest.java
  src/test/java/marquez/db/JobRunDaoTest.java
  src/test/java/marquez/service/JobServiceIntegrationTest.java
  src/test/java/marquez/service/JobServiceTest.java
  src/test/java/marquez/service/NamespaceServiceTest.java
Labels: cleanup, enhancement, review

#345 Bump spotless plugin to 3.18.0
  build.gradle
  src/main/java/marquez/service/models/JobRunState.java
  src/test/java/marquez/api/mappers/NamespaceResponseMapperTest.java
Labels: review

#346 Bump dropwizard to 1.3.9
  build.gradle
Labels: review

#342 Add -parameters compiler flag
  build.gradle
Labels: cleanup, review

#348 Rename throwable field
  src/main/java/marquez/MarquezException.java
  src/main/java/marquez/service/exceptions/MarquezServiceException.java
Labels: review

#349 Update job request
  src/main/java/marquez/api/models/CreateJobRequest.java
  src/main/java/marquez/api/models/JobRequest.java
  src/main/java/marquez/api/resources/JobResource.java
  src/test/java/marquez/api/JobIntegrationTest.java
  src/test/java/marquez/api/JobResourceTest.java
Labels: api, cleanup, review
