Repository MarquezProject/marquez, pull requests merged in 2019-01, with the labels that each got.

#225 Remove BaseResource
  src/main/java/marquez/api/resources/BaseResource.java
Labels: cleanup, review

#223 Use 'id' as path variable in job runs endpoint
  docs/openapi.yml
  src/main/java/marquez/api/resources/JobResource.java
Labels: review

#217 Add build info to jar manifest
  build.gradle
Labels: review

#218 Bump gradle version
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: review

#219 Add support for admin port override and expose admin page
  Dockerfile
  config.example.yml
  docker-compose.yml
Labels: review

#238 Add class RunId
  src/main/java/marquez/common/models/RunId.java
  src/test/java/marquez/common/models/RunIdTest.java
Labels: review

#236 Fix dataset urn naming in job list example [skip ci]
  docs/openapi.yml
Labels: docs

#245 Rename RunArgsDao to JobRunArgsDao
  src/main/java/marquez/MarquezApp.java
  src/main/java/marquez/db/JobRunArgsDao.java
  src/main/java/marquez/db/JobRunDao.java
  src/main/java/marquez/db/mappers/JobRunArgsRowMapper.java
  src/main/java/marquez/service/JobService.java
  src/test/java/marquez/api/JobIntegrationTest.java
  src/test/java/marquez/db/JobRunArgsDaoTest.java
  src/test/java/marquez/db/JobRunDaoTest.java
  src/test/java/marquez/service/JobServiceIntegrationTest.java
  src/test/java/marquez/service/JobServiceTest.java
Labels: cleanup, review

#246 Drop 'v' prefix from docker img tag
  .circleci/config.yml
  docker/build-and-push.sh
Labels: cleanup, review

#241 Instrument for jdbi metrics.
  build.gradle
  config.example.yml
  src/main/java/marquez/MarquezApp.java
Labels: review
