Repository MarquezProject/marquez, pull requests merged in 2020-01, with the labels that each got.

#684 Fix error on tag exists
  src/main/java/marquez/api/DatasetResource.java
  src/main/java/marquez/db/DatasetDao.java
  src/main/java/marquez/service/TagService.java
  src/main/java/marquez/service/mappers/Mapper.java
Labels: bug

#685 Add Utils.toUuid()
  src/main/java/marquez/api/JobResource.java
  src/main/java/marquez/api/exceptions/RunNotValidException.java
  src/main/java/marquez/common/Utils.java
Labels: in progress

#701 Added Location header to run creation
  src/main/java/marquez/api/JobResource.java
  src/test/java/marquez/MarquezAppIntegrationTest.java
Labels: review
