Repository MarquezProject/marquez, pull requests merged in 2020-11, with the labels that each got.

#827 Integrate Web
  .circleci/config.yml
  .circleci/get-docker.sh
  .dockerignore
  README.md
  docker-compose.seed.yml
  docker-compose.yml
  docker/up.sh
  web/.circleci/config.yml
  web/.dockerignore
  web/.github/PULL_REQUEST_TEMPLATE.md
  web/CODE_OF_CONDUCT.md
  web/CONTRIBUTING.md
  web/README.md
  web/RELEASE.md
  web/docker-compose.dev.yml
  web/docker-compose.yml
Labels: review

#837 Bump guava to 30.0-jre
  build.gradle
Labels: review

#836 Bump jdbi3 to 3.17.0
  build.gradle
Labels: review

#835 Bump dropwizard to 2.0.15
  build.gradle
Labels: review

#834 Bump shadow to 6.1.0
  build.gradle
Labels: review

#833 Bump dependency-license-report to 1.16
  build.gradle
Labels: review

#843 Add module section to README.md and other minor changes
  README.md
Labels: docs, review

#832 Bump spotless to 5.8.1
  build.gradle
Labels: review

#831 Bump test-logger to 2.1.1
  build.gradle
Labels: review

#844 Fix docker/up.sh to allow for multiple flags
  docker-compose.dev.yml
  docker-compose.yml
  docker/up.sh
Labels: review

#846 Add link to API spec in quickstart [skip ci]
  README.md
Labels: docs
