Repository MarquezProject/marquez, pull requests merged in 2020-12, with the labels that each got.

#848 docs/openapi.yml -> spec/openapi.yml
  CONTRIBUTING.md
  spec/openapi.yml
Labels: review

#861 Update contributor covenant to v2.0
  CODE_OF_CONDUCT.md
  README.md
Labels: review

#860 Add marquez-chart
  chart/Chart.yaml
  chart/LICENSE
  chart/README.md
  chart/templates/NOTES.txt
  chart/templates/_helpers.tpl
  chart/templates/configmap.yaml
  chart/templates/deployment.yaml
  chart/templates/ingress.yaml
  chart/templates/service.yaml
  chart/templates/tests/test-connection.yaml
  chart/values.yaml
Labels: review

#859 Add marquez-python
  clients/python/.circleci/config.yml
  clients/python/.circleci/release_check.sh
  clients/python/.gitignore
  clients/python/CODE_OF_CONDUCT.md
  clients/python/CONTRIBUTING.md
  clients/python/LICENSE
  clients/python/Makefile
  clients/python/README.md
  clients/python/RELEASING.md
  clients/python/__init__.py
  clients/python/codecov.yml
  clients/python/marquez_client/__init__.py
  clients/python/marquez_client/backend.py
  clients/python/marquez_client/client.py
  clients/python/marquez_client/client_wo.py
  clients/python/marquez_client/clients.py
  clients/python/marquez_client/constants.py
  clients/python/marquez_client/errors.py
  clients/python/marquez_client/file_backend.py
  clients/python/marquez_client/http_backend.py
  clients/python/marquez_client/log_backend.py
  clients/python/marquez_client/models.py
  clients/python/marquez_client/utils.py
  clients/python/marquez_client/version.py
  clients/python/release.sh
  clients/python/setup.cfg
  clients/python/setup.py
  clients/python/test-requirements.txt
  clients/python/tests/__init__.py
  clients/python/tests/pytest.ini
  clients/python/tests/resources/post.json
  clients/python/tests/resources/put.json
  clients/python/tests/test_backend.py
  clients/python/tests/test_log_backend.py
  clients/python/tests/test_marquez_client.py
  clients/python/tests/test_marquez_clients.py
  clients/python/tests/test_marquez_wo_client.py
  clients/python/tests/test_marquez_wo_client_file.py
  clients/python/tests/test_marquez_wo_client_http.py
  clients/python/tests/test_marquez_wo_client_log.py
  clients/python/tests/test_utils.py
  clients/python/tox.ini
Labels: review

#867 Add marquez-airflow
  integrations/airflow/.circleci/config.yml
  integrations/airflow/.circleci/get-docker-compose.sh
  integrations/airflow/.circleci/release_check.sh
  integrations/airflow/.gitignore
  integrations/airflow/CHANGELOG.md
  integrations/airflow/CODE_OF_CONDUCT.md
  integrations/airflow/CONTRIBUTING.md
  integrations/airflow/LICENSE
  integrations/airflow/README.md
  integrations/airflow/marquez_airflow/__init__.py
  integrations/airflow/marquez_airflow/dag.py
  integrations/airflow/marquez_airflow/extractors/__init__.py
  integrations/airflow/marquez_airflow/extractors/bigquery_extractor.py
  integrations/airflow/marquez_airflow/extractors/postgres_extractor.py
  integrations/airflow/marquez_airflow/extractors/sql/__init__.py
  integrations/airflow/marquez_airflow/extractors/sql/experimental/__init__.py
  integrations/airflow/marquez_airflow/extractors/sql/experimental/parser.py
  integrations/airflow/marquez_airflow/extractors/sql/parser.py
  integrations/airflow/marquez_airflow/marquez.py
  integrations/airflow/marquez_airflow/models.py
  integrations/airflow/marquez_airflow/utils.py
  integrations/airflow/marquez_airflow/version.py
  integrations/airflow/release.sh
  integrations/airflow/setup.cfg
  integrations/airflow/setup.py
  integrations/airflow/test-requirements.txt
  integrations/airflow/tests/__init__.py
  integrations/airflow/tests/conftest.py
  integrations/airflow/tests/extractors/job_details.json
  integrations/airflow/tests/extractors/out_table_details.json
  integrations/airflow/tests/extractors/sql/test_parser.py
  integrations/airflow/tests/extractors/table_details.json
  integrations/airflow/tests/extractors/test_bigquery_extractor.py
  integrations/airflow/tests/extractors/test_postgres_extractor.py
  integrations/airflow/tests/integration/Dockerfile
  integrations/airflow/tests/integration/airflow/config/log_config.py
  integrations/airflow/tests/integration/airflow/dags/orders_popular_day_of_week.py
  integrations/airflow/tests/integration/docker-compose.yml
  integrations/airflow/tests/integration/docker/entrypoint.sh
  integrations/airflow/tests/integration/docker/init-db.sh
  integrations/airflow/tests/integration/docker/up.sh
  integrations/airflow/tests/integration/docker/wait-for-it.sh
  integrations/airflow/tests/integration/integration.py
  integrations/airflow/tests/mocks/__init__.py
  integrations/airflow/tests/mocks/git_mock.py
  integrations/airflow/tests/mocks/marquez_client.py
  integrations/airflow/tests/mocks/mock_id_mapping.py
  integrations/airflow/tests/pytest.ini
  integrations/airflow/tests/test_dags/test_dummy_dag.py
  integrations/airflow/tests/test_location.py
  integrations/airflow/tests/test_marquez_dag.py
  integrations/airflow/tests/test_utils.py
  integrations/airflow/tests/util.py
Labels: review

#868 Remove related proj section
  README.md
Labels: docs, review

#870 Add airflow task lifecycle documentation
  integrations/airflow/docs/task-lifecycle.md
  integrations/airflow/docs/task_lifecycle_diagram.png
Labels: airflow, docs

#871 Add dependencies between DAGS in Airflow example
  examples/airflow/dags/delivery_times_7_days.py
  examples/airflow/dags/email_discounts.py
  examples/airflow/dags/etl_categories.py
  examples/airflow/dags/etl_customers.py
  examples/airflow/dags/etl_delivery_7_days.py
  examples/airflow/dags/etl_drivers.py
  examples/airflow/dags/etl_menu_items.py
  examples/airflow/dags/etl_menus.py
  examples/airflow/dags/etl_order_status.py
  examples/airflow/dags/etl_orders.py
  examples/airflow/dags/etl_orders_7_days.py
  examples/airflow/dags/etl_restaurants.py
  examples/airflow/dags/new_food_deliveries.py
  examples/airflow/dags/orders_popular_day_of_week.py
  examples/airflow/docker-compose.yml
Labels: airflow, review

#872 Add link to Marquez UI in Airflow quickstart [skip ci]
  examples/airflow/README.md
  examples/airflow/docker/up.sh
Labels: airflow, docs

#869 Fix task completion time to use airflow task end time instead of dag end time
  integrations/airflow/marquez_airflow/dag.py
  integrations/airflow/marquez_airflow/marquez.py
  integrations/airflow/tests/test_marquez_dag.py
Labels: airflow, blocked
