Repository MarquezProject/marquez, pull requests merged in 2021-03, with the labels that each got.

#1048 Run renovate on weekends
  renovate.json
Labels: review

#1053 Override PR target for renovate
  renovate.json
Labels: review

#1057 Add .pre-commit-config.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: review

#1061 Ensure marquez.DAG is (de)serializable
  integrations/airflow/marquez_airflow/dag.py
  integrations/airflow/marquez_airflow/marquez.py
  integrations/airflow/marquez_airflow/utils.py
  integrations/airflow/tests/test_marquez_dag.py
Labels: airflow

#1087 Minor doc updates to setting up java8 for spark [skip ci]
  README.md
Labels: review

#943 Add steps to airflow example [skip ci]
  examples/airflow/.gitignore
  examples/airflow/README.md
  examples/airflow/dags/delivery_times_7_days.py
  examples/airflow/dags/email_discounts.py
  examples/airflow/dags/etl_categories.py
  examples/airflow/dags/etl_customers.py
  examples/airflow/dags/etl_delivery_7_days.py
  examples/airflow/dags/etl_drivers.py
  examples/airflow/dags/etl_menu_items.py
  examples/airflow/dags/etl_menus.py
  examples/airflow/dags/etl_order_status.py
  examples/airflow/dags/etl_orders.py
  examples/airflow/dags/etl_orders_7_days.py
  examples/airflow/dags/etl_restaurants.py
  examples/airflow/dags/new_food_deliveries.py
  examples/airflow/dags/orders_popular_day_of_week.py
  examples/airflow/docker-compose.yml
  examples/airflow/docker/init-db.sh
  examples/airflow/docker/up.sh
  examples/airflow/docs/dag-view.png
  examples/airflow/docs/data-model.md
  examples/airflow/docs/lineage-view-dataset.png
  examples/airflow/docs/lineage-view-job-successful.png
  examples/airflow/docs/lineage-view-job.png
  examples/airflow/docs/search-job-failure.png
  examples/airflow/docs/search.png
  examples/airflow/requirements.txt
Labels: airflow, review

#1150 Add sentry config
  api/build.gradle
  marquez.example.yml
Labels: review

#1149 Add docs on applying db migrations manually
  api/src/main/java/marquez/MarquezConfig.java
  api/src/main/java/marquez/db/DbMigration.java
  docs/db-migrations.md
  marquez.example.yml
Labels: docs

#1170 Fix url encoding for java 8 in client
  .circleci/config.yml
  clients/java/src/main/java/marquez/client/FileBackend.java
  clients/java/src/main/java/marquez/client/MarquezWriteOnlyClientImpl.java
  clients/java/src/test/java/marquez/client/MarquezWriteOnlyClientTest.java
Labels: review

#1171 Add lineage endpoint to api spec
  docs/openapi.html
  spec/openapi.yml
Labels: docs, review

#1145 Added Secrets to Helm Chart
  chart/README.md
  chart/templates/_helpers.tpl
  chart/templates/marquez/deployment.yaml
  chart/templates/marquez/secret.yaml
  chart/values.yaml
Labels: review

#1172 Prepare release 0.13.0
  CHANGELOG.md
  api/gradle.properties
  chart/Chart.yaml
  chart/README.md
  chart/values.yaml
  clients/java/README.md
  clients/java/gradle.properties
  clients/python/marquez_client/version.py
  clients/python/setup.cfg
  docs/openapi.html
  gradle.properties
  integrations/airflow/marquez_airflow/version.py
  integrations/airflow/setup.cfg
  integrations/airflow/setup.py
  integrations/airflow/test-requirements.txt
  integrations/spark/README.md
  integrations/spark/gradle.properties
  spec/openapi.yml
Labels: review
