Repository MarquezProject/marquez, pull requests merged in 2023-05, with the labels that each got.

#2477 update releasing instructions
  CHANGELOG.md
  RELEASING.md
Labels: docs

#2488 Skip regex after `postgresql` in `chart/values.yaml`
  new-version.sh
Labels: review

#2491 Remove volumes on `docker/down.sh`
  .circleci/api-load-test.sh
  docker/down.sh
  docker/up.sh
  new-version.sh
Labels: docker

#2496 fix broken link in Airflow example
  examples/airflow/README.md
Labels: docs, example

#2493 Add OL compatibility table
  README.md
  RELEASING.md
Labels: docs
